export default {
  name: 'ProjectTable',
  props: {
    dataTable: Array,
  },
  data() {
    return {
      table: {
        content: [
          {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          }, {
            id: '00001',
            name: '神奇动物在哪里',
            maker: '华纳影业',
            registerTime: '登记时间',
          },
        ],
      },
    };
  },
};
